spring:
  application.name: Stock Price Client
  output.ansi.enabled: always
algod:
  url: ${ALGOD_URL}
  port: ${ALGOD_PORT}
  token: # intentionally left empty as it's not needed for algoexplorer's API
  indexer:
    url: ${INDEXER_URL}
    port: ${INDEXER_PORT}